name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      # Sadece gerekli dosyaları ayrı bir klasöre kopyala
      - name: Prepare site
        run: |
          mkdir out
          cp -r index.html assets css js out/ 2>/dev/null || true
          # SPA ise 404 yönlendirmesi
          [ -f out/index.html ] && cp out/index.html out/404.html

      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
      - id: deployment
        uses: actions/deploy-pages@v4
